---
- name: Enviar todas as variáveis do Ansible para o Jinja2 Playground
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Debug services
      ansible.builtin.debug:
        var: services

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Debug packages
      ansible.builtin.debug:
        var: packages

    - name: Send Ansible variables to Jinja2 Playground
      ansible.builtin.uri:
        url: "http://127.0.0.1:8000/load_ansible_vars"
        method: POST
        body_format: json
        body:
          variables_b64: "{{ vars.ansible_facts | to_json | b64encode }}"
          summary:
            total_variables: "{{ vars.ansible_facts | length }}"
            my_test: "test_value"
            source: "all_variables"
        headers:
          Content-Type: "application/json"
        timeout: 10
      register: ansible_vars_response

    - name: "Process API response"
      ansible.builtin.debug:
        var: ansible_vars_response
